<?php
/**
 * PHP SDK for the PaymoApp API
 * Package Source Code: https://github.com/jcolombo/paymo-api-php
 * Paymo API Documentation : https://github.com/paymoapp/api
 *
 * MIT License
 * Copyright (c) 2020 - Joel Colombo <jc-dev@360psg.com>
 * Last Updated : 3/18/20, 1:25 PM
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 *
 * ======================================================================================
 * REQUEST ABSTRACTION - HTTP REQUEST CONFIGURATION CONTAINER
 * ======================================================================================
 *
 * This utility class encapsulates all the configuration needed for an HTTP request
 * to the Paymo API. It abstracts the request details (method, URL, data, etc.) from
 * the actual HTTP execution, allowing the Request class to build requests that are
 * then executed by Paymo::execute().
 *
 * KEY FEATURES:
 * -------------
 * - Stores HTTP method (GET, POST, PUT, DELETE)
 * - Manages request mode (JSON or multipart for file uploads)
 * - Contains resource URL path
 * - Holds request data for POST/PUT operations
 * - Stores include and where query parameters
 * - Manages file upload configurations
 * - Generates consistent cache keys for GET requests
 *
 * CACHE KEY GENERATION:
 * ---------------------
 * The makeCacheKey() method creates deterministic cache keys based on:
 * - Resource URL
 * - Include parameters
 * - Where parameters
 *
 * This ensures identical requests always produce the same cache key.
 *
 * USAGE FLOW:
 * -----------
 * 1. Request class creates RequestAbstraction instance
 * 2. Properties are populated with request configuration
 * 3. For GET requests, makeCacheKey() generates cache key
 * 4. Paymo::execute() receives the abstraction and performs HTTP call
 * 5. Response is stored in RequestResponse
 *
 * @package    Jcolombo\PaymoApiPhp\Utility
 * @author     Joel Colombo <jc-dev@360psg.com>
 * @copyright  2020 Joel Colombo
 * @license    MIT
 * @version    0.5.6
 * @link       https://github.com/jcolombo/paymo-api-php
 *
 * @see        Request Creates and populates RequestAbstraction objects
 * @see        Paymo::execute() Executes requests based on abstraction config
 * @see        RequestResponse Contains the response from executed requests
 */

namespace Jcolombo\PaymoApiPhp\Utility;

/**
 * Data container for HTTP request configuration.
 *
 * RequestAbstraction holds all the parameters needed to make an HTTP request
 * to the Paymo API. It separates request building from execution, allowing
 * the same abstraction to be cached, logged, or inspected before execution.
 *
 * @package Jcolombo\PaymoApiPhp\Utility
 */
class RequestAbstraction
{
    /**
     * Unique cache key for this request.
     *
     * Generated by makeCacheKey() for GET requests. The key is based on the
     * URL, include, and where parameters, ensuring identical requests always
     * produce the same key. Null indicates the request is not cacheable
     * (non-GET requests).
     *
     * Format: 'paymoapi-{md5hash}'
     *
     * @var string|null Cache key string, or null if not cacheable
     *
     * @see makeCacheKey() Method that generates this key
     */
    public ?string $cacheKey = null;

    /**
     * The HTTP method for this request.
     *
     * Valid values:
     * - 'GET': Retrieve resource(s)
     * - 'POST': Create new resource
     * - 'PUT': Update existing resource
     * - 'DELETE': Remove resource
     *
     * @var string HTTP method, defaults to 'GET'
     */
    public string $method = 'GET';

    /**
     * The request body encoding mode.
     *
     * Determines how request data is encoded:
     * - 'json': Send data as JSON (default, used for most requests)
     * - 'multipart': Send as multipart/form-data (used for file uploads)
     *
     * @var string Either 'json' or 'multipart', defaults to 'json'
     */
    public string $mode = 'json';

    /**
     * The API resource path.
     *
     * Appended to the base API URL to form the complete endpoint.
     * Examples: 'projects', 'projects/123', 'tasks', 'clients/456/projects'
     *
     * Do not include query parameters - those are handled via include/where.
     *
     * @var string|null Resource path, or null if not set
     */
    public ?string $resourceUrl = null;

    /**
     * Request body data for POST/PUT requests.
     *
     * Associative array of field values to send. For creating or updating
     * resources, this contains the entity properties to save.
     *
     * Example: ['name' => 'New Project', 'client_id' => 123]
     *
     * @var array<string, mixed>|null Data array, or null for GET/DELETE
     */
    public ?array $data = null;

    /**
     * The include query parameter value.
     *
     * Comma-separated string of relationships to include in the response.
     * Pre-scrubbed and validated before being set.
     *
     * Example: 'client,tasklists,users'
     *
     * @var string|null Include parameter, or null if none
     */
    public ?string $include = null;

    /**
     * The where query parameter value.
     *
     * Compiled WHERE condition string for server-side filtering.
     * Pre-scrubbed and validated from RequestCondition objects.
     *
     * Example: 'active=true and budget>1000'
     *
     * @var string|null Where parameter, or null if none
     */
    public ?string $where = null;

    /**
     * Files to upload with this request.
     *
     * Associative array mapping property names to file paths.
     * When set, the request mode should be 'multipart'.
     *
     * Example: ['file' => '/path/to/document.pdf']
     *
     * @var array<string, string>|null File mappings, or null if none
     */
    public ?array $files = null;

    /**
     * Generate a deterministic cache key for this request.
     *
     * Creates an MD5-based cache key from the request's URL, include, and where
     * parameters. Only generates keys for GET requests (as other methods modify
     * data and shouldn't be cached).
     *
     * KEY FORMAT:
     * -----------
     * 'paymoapi-{md5(resourceUrl:include=X&where=Y)}'
     *
     * The same request parameters will always produce the same key, enabling
     * reliable cache lookups.
     *
     * USAGE:
     * ------
     * ```php
     * $abstraction = new RequestAbstraction();
     * $abstraction->resourceUrl = 'projects';
     * $abstraction->include = 'client,tasks';
     * $abstraction->where = 'active=true';
     * $abstraction->makeCacheKey();
     *
     * echo $abstraction->cacheKey;
     * // 'paymoapi-a1b2c3d4e5f6...'
     * ```
     *
     * @param bool $force If true, regenerates key even if one exists.
     *                    If false, preserves existing key. Defaults to true.
     *
     * @return $this Returns self for method chaining
     */
    public function makeCacheKey(bool $force = true) : RequestAbstraction
    {
        if ($this->method === 'GET') {
            if (!$force && !is_null($this->cacheKey)) {
                return $this;
            }
            $this->cacheKey = 'paymoapi-'.md5($this->resourceUrl.':include='.$this->include.'&where='.$this->where);
        }

        return $this;
    }
}